<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class AdminDataSeeder extends Seeder
{
    public function run(): void
    {
        $users = User::all();

        if ($users->count() < 10) {
            $this->command->info('Not enough users to seed admin data. Run DiscoverUsersSeeder first.');
            return;
        }

        $now = now();
        $this->command->info('Seeding Admin Data (Matches, Alarms, Reports, Sessions)...');

        $reports = [];
        $alarms = [];
        $matches = [];
        $sessions = [];

        $reasons = ['spam', 'harassment', 'fake_account', 'impersonation', 'inappropriate_behavior'];
        $statuses = ['pending', 'under_review', 'resolved', 'dismissed'];
        $alarmTypes = ['crush_nearby', 'mutual_crush_nearby', 'match_created', 'system_notification'];

        for ($i = 0; $i < 30; $i++) {
            $currentDate = $now->copy()->subDays($i);

            // Seed 1-5 reports per day
            $numReports = rand(1, 5);
            for ($j = 0; $j < $numReports; $j++) {
                $reporter = $users->random();
                $reported = $users->except($reporter->id)->random();
                $reports[] = [
                    'id' => Str::uuid()->toString(),
                    'reporter_id' => $reporter->id,
                    'reported_user_id' => $reported->id,
                    'reason' => $reasons[array_rand($reasons)],
                    'description' => 'Generated by seeder for analytics testing.',
                    'status' => $statuses[array_rand($statuses)],
                    'created_at' => $currentDate,
                    'updated_at' => $currentDate,
                ];
            }

            // Seed 10-30 alarms per day
            $numAlarms = rand(10, 30);
            for ($j = 0; $j < $numAlarms; $j++) {
                $user = $users->random();
                $triggeredBy = $users->except($user->id)->random();
                $alarms[] = [
                    'id' => Str::uuid()->toString(),
                    'user_id' => $user->id,
                    'triggered_by_user_id' => $triggeredBy->id,
                    'type' => $alarmTypes[array_rand($alarmTypes)],
                    'status' => 'delivered',
                    'triggered_at' => $currentDate,
                    'expires_at' => $currentDate->copy()->addDay(),
                    'created_at' => $currentDate,
                    'updated_at' => $currentDate,
                ];
            }

            // Seed 2-8 matches per day
            $numMatches = rand(2, 8);
            for ($j = 0; $j < $numMatches; $j++) {
                $u1 = $users->random();
                $u2 = $users->except($u1->id)->random();

                // Ensure u1 < u2 to avoid unique constraint violations
                if ($u1->id > $u2->id) {
                    $temp = $u1;
                    $u1 = $u2;
                    $u2 = $temp;
                }

                $matches[] = [
                    'id' => Str::uuid()->toString(),
                    'user_one_id' => $u1->id,
                    'user_two_id' => $u2->id,
                    'matched_at' => $currentDate,
                    'created_at' => $currentDate,
                    'updated_at' => $currentDate,
                ];
            }

            // Seed 20-50 active sessions per day
            $numSessions = rand(20, 50);
            for ($j = 0; $j < $numSessions; $j++) {
                $user = $users->random();
                $sessions[] = [
                    'id' => Str::uuid()->toString(),
                    'user_id' => $user->id,
                    'ip_address' => '127.0.0.1',
                    'user_agent' => 'Seeder',
                    'payload' => '',
                    'last_activity' => $currentDate->timestamp,
                ];
            }
        }

        // Remove duplicate matches mathematically (for safety)
        $uniqueMatches = collect($matches)->unique(function ($item) {
            return $item['user_one_id'].'-'.$item['user_two_id'];
        })->toArray();

        DB::table('reports')->insert($reports);
        DB::table('alarms')->insert($alarms);
        DB::table('matches')->insert($uniqueMatches);
        DB::table('sessions')->insert($sessions);

        $this->command->info('Admin Data Seeded successfully!');
    }
}
